### ISSUE TITLE
Going live and charging money

### ISSUE THREAD

**Issue by stevenday** [mysociety/mapit-bulk-processing#1]
- [x] Switch to live mySociety Stripe api keys
- [x] Set up live site on https
- [ ] Come up with a name ("bulk lookup" isn't a term any of our previous customers have used) Most common names are - map/match spreadsheet/data mapit/constituencies/wards
- [ ] Send VAT invoices for successful payments (seems we might be able to pass an email to Stripe and hack this into a description for the time being?

Promotion ideas:
-  [ ] Link from mapit's homepage?
-  [ ] Blog post
-  [ ] Ask myf to promo on social media
-  [ ] Create a voucher code for people who helped beta test to get 50% off.
-  [ ] Email beta testers (and previous mapit bulk enquiries people) to soft launch it it.

**Comment by dracos** [comment]
Moved to other repo.
